import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import I18nProvider from "./i18n-provider";
import Navbar from "@/components/Navbar/Navbar";
import TabletNav from "@/components/Navbar/TabletNav";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prothom Alo Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Get the language from your i18n instance or from the URL
  const lang = "en"; // Replace with your logic

  return (
    <html lang={lang}>
      <Navbar></Navbar>

      {/* <MobileNav></MobileNav> */}
      <body>{children}</body>
      <Footer></Footer>
    </html>
  );
}
